### ISSUE TITLE
超龄结婚 bug

### ISSUE THREAD

**Issue by QoooQ** [mapleobserver/wsmud-script#14]
超龄结婚 现在无法结婚 试了五次了 忘忧草10 醉仙酿10  是不是改了 小樓手动往南往北没出现选项

                    go south
                    go north
                @tip 我答应你
                answer s3
                @tip 月圆之夜就是你和青青拜堂之时

**Comment by mapleobserver** [comment]
超龄结婚过程，网页要保持在前台，否则失败概率极高。
